import streamlit as st
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

st.title("LAWS90286 - D1")

# 推测的两行：首次运行时创建 name
if "name" not in st.session_state:
    st.session_state.name = ""

if "button_value" not in st.session_state:
    st.session_state.button_value = False

# 1.Asks the user to enter their name.
st.header("Part 1 - Get Name")
st.session_state.name = st.text_input("What's your name?")

# 2.If the user enters their name and clicks a button, displays a welcome message to the user.
st.header("Part 2 - Click Button")
st.session_state.button_value = st.button("Click Me")

st.header("Part 3 - Display Name (Hardcoded)")

if st.session_state.name != "" and st.session_state.button_value == True:
    st.write(f"Hello, {st.session_state.name}")

    # 3.The welcome message should be generated by GPT-4o.
    st.header("Part 4 - Display Name (AI Generated)")

    client = OpenAI()

    response = client.responses.create(
        model="gpt-4o",
        input=f"Greet {st.session_state.name} and make them welcome.",
    )

    st.write(response.output_text)

# 4.The user should be able to select different personas to be welcomed by.
st.header("Part 5 - Display Welcome based on a Persona")

st.session_state.option = st.selectbox(
    "What persona?",
    ("Shark", "Cow", "Clown", "Donald Trump"),
)

if st.session_state.name != "" and st.session_state.button_value == True and st.session_state.option != "":
    response = client.responses.create(
        model="gpt-4o",
        instructions=f"You must respond as if you are a: {st.session_state.option}",
        input=f"Greet {st.session_state.option} and make them welcome.",
    )

    st.write(response.output_text)

